package vista;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.TablaHash;
import modelo.Usuario;

/**
 *
 * @author Nelson
 */
public class frameLogin extends javax.swing.JFrame {
    
    TablaHash tablaLogin = new TablaHash();
    /**
     * Creates new form frameLogin
     */
    public frameLogin() {
        initComponents();
        
        datosUsuarios();
        imageIconCambiar(frameLogin.class.getResource("/images/ocultar.png"), passicon, 20);
    }

    public void datosUsuarios(){
        tablaLogin.insertarTabHash("admin", new Usuario("admin", "Administrador", "2021-01-01", "2021-01-02"));
        tablaLogin.insertarTabHash("MariaGomez", new Usuario("ufufu", "Empleado", "2021-01-03", "2021-01-04"));
        tablaLogin.insertarTabHash("LuisRamirez", new Usuario("123456", "Vendedor", "2021-01-05", "2021-01-06"));
        tablaLogin.insertarTabHash("CarlosTorres", new Usuario("abcd123", "Cajero", "2021-01-07", "2021-01-08"));
        tablaLogin.insertarTabHash("AnaLopez", new Usuario("pass1234", "Cliente", "2021-01-09", "2021-01-10"));
        tablaLogin.insertarTabHash("PedroGarcia", new Usuario("qwerty", "Vendedor", "2021-01-11", "2021-01-12"));
        tablaLogin.insertarTabHash("JuliaRojas", new Usuario("password", "Cliente", "2021-01-13", "2021-01-14"));
        tablaLogin.insertarTabHash("DiegoVargas", new Usuario("hello123", "Cajero", "2021-01-15", "2021-01-16"));
        tablaLogin.insertarTabHash("RosaFlores", new Usuario("abc123", "Cliente", "2021-01-17", "2021-01-18"));
        tablaLogin.insertarTabHash("Nelson", new Usuario("letmein", "Administrador", "2021-01-19", "2021-01-20"));
    }
    public TablaHash.EntradaHash[] entradaLogin(){
        return tablaLogin.getTabla();
    }
    
    public void imageIconCambiar(URL resource, JLabel iconoMod, int tamaño) {
        ImageIcon iconLogo = new ImageIcon(resource);
        Image image = iconLogo.getImage();
        Image imgRescalado = image.getScaledInstance(tamaño, tamaño, java.awt.Image.SCALE_SMOOTH);
        iconLogo = new ImageIcon(imgRescalado);
        iconoMod.setIcon(iconLogo);
    }
    public void errorUsuario(){
        imageIconCambiar(frameLogin.class.getResource("/images/infoerror.png"), errorUs,20);
    }
    public void errorContraseña(){
        imageIconCambiar(frameLogin.class.getResource("/images/infoerror.png"), errorCon,20);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitbtn = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        minbtn = new javax.swing.JPanel();
        btnMin = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        errorUs = new javax.swing.JLabel();
        errorCon = new javax.swing.JLabel();
        passicon = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        campoUsu = new javax.swing.JTextField();
        sepUs = new javax.swing.JSeparator();
        sepCon = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JPanel();
        Ingresar = new javax.swing.JLabel();
        btnAcerca = new javax.swing.JPanel();
        Acerca = new javax.swing.JLabel();
        TItulo = new javax.swing.JLabel();
        campoCon = new javax.swing.JPasswordField();
        Logo = new javax.swing.JLabel();
        LoginBackrgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitbtn.setBackground(new java.awt.Color(89, 89, 89));

        btnExit.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        header.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 30, -1));

        minbtn.setBackground(new java.awt.Color(89, 89, 89));

        btnMin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnMin.setForeground(new java.awt.Color(255, 255, 255));
        btnMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMin.setText("_");
        btnMin.setToolTipText("");
        btnMin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minbtnLayout = new javax.swing.GroupLayout(minbtn);
        minbtn.setLayout(minbtnLayout);
        minbtnLayout.setHorizontalGroup(
            minbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        minbtnLayout.setVerticalGroup(
            minbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        header.add(minbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 30, 30));

        titulo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Ingresar Cuenta");
        header.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 30));

        errorUs.setToolTipText("");
        errorUs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(errorUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 20, 20));

        errorCon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(errorCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 20, 20));

        passicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passiconMouseClicked(evt);
            }
        });
        jPanel1.add(passicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 20, 20));

        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        lblUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContrasena.setText("Contraseña");
        lblContrasena.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 20));

        campoUsu.setBackground(new java.awt.Color(51, 51, 51));
        campoUsu.setForeground(new java.awt.Color(255, 255, 255));
        campoUsu.setBorder(null);
        campoUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoUsuKeyPressed(evt);
            }
        });
        jPanel1.add(campoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 200, 20));
        jPanel1.add(sepUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, -1));
        jPanel1.add(sepCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 180, -1));

        btnIngresar.setBackground(new java.awt.Color(102, 102, 102));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });

        Ingresar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ingresar.setText("Ingresar");

        javax.swing.GroupLayout btnIngresarLayout = new javax.swing.GroupLayout(btnIngresar);
        btnIngresar.setLayout(btnIngresarLayout);
        btnIngresarLayout.setHorizontalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnIngresarLayout.setVerticalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, -1));

        btnAcerca.setBackground(new java.awt.Color(102, 102, 102));
        btnAcerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcercaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcercaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcercaMouseExited(evt);
            }
        });

        Acerca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Acerca.setForeground(new java.awt.Color(255, 255, 255));
        Acerca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Acerca.setText("Acerca del programa");

        javax.swing.GroupLayout btnAcercaLayout = new javax.swing.GroupLayout(btnAcerca);
        btnAcerca.setLayout(btnAcercaLayout);
        btnAcercaLayout.setHorizontalGroup(
            btnAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAcercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Acerca, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnAcercaLayout.setVerticalGroup(
            btnAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAcercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Acerca, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 130, -1));

        TItulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        TItulo.setForeground(new java.awt.Color(255, 255, 255));
        TItulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TItulo.setText("Calculadora IPv4 & subredes");
        jPanel1.add(TItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 290, -1));

        campoCon.setBackground(new java.awt.Color(51, 51, 51));
        campoCon.setForeground(new java.awt.Color(255, 255, 255));
        campoCon.setBorder(null);
        campoCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoConKeyPressed(evt);
            }
        });
        jPanel1.add(campoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 180, 20));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconRed2.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 130, 130));

        LoginBackrgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpIcon.jpg"))); // NOI18N
        jPanel1.add(LoginBackrgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 330, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passiconMouseClicked
        mostrarContrasena = !mostrarContrasena;
        URL resource;
        if (mostrarContrasena) {
            campoCon.setEchoChar((char) 0); // Mostrar contraseña sin asteriscos
            campoCon.setEchoChar((char) 0);
            resource = frameLogin.class.getResource("/images/mostrar.png");
        } else {
            campoCon.setEchoChar('*'); // Mostrar contraseña con asteriscos
            campoCon.setEchoChar('*');
            resource = frameLogin.class.getResource("/images/ocultar.png");
        }
        imageIconCambiar(resource, passicon, 20);
    }//GEN-LAST:event_passiconMouseClicked

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        btnIngresar.setBackground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        btnIngresar.setBackground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        String contraseña = new String(campoCon.getPassword());
        String usuario = campoUsu.getText();

        String mensaje = "";
        boolean datosValidos;

        if (usuario.equals("") && contraseña.equals("")) {
            datosValidos = false;
            mensaje = "Falta Usuario y Contraseña";
            errorContraseña();
            errorUsuario();
        } else if (usuario.equals("")) {
            datosValidos = false;
            mensaje = "Falta Usuario";
            errorCon.setIcon(null);
            errorUsuario();
        } else if (contraseña.equals("")) {
            datosValidos = false;
            mensaje = "Falta Contraseña";
            errorUs.setIcon(null);
            errorContraseña();
        } else {
            datosValidos = true;

            errorUs.setIcon(null);
            errorCon.setIcon(null);
        }

        //Si la contraseña y usuario es correcta = TRUE = DATOSVALIDACION
        if (datosValidos) {

            TablaHash tblLogin = tablaLogin;
            Usuario userdato = tblLogin.obtenerValorTabHash(usuario);

            if (userdato != null) {
                if (contraseña.equals(userdato.getContraseña())) {
                    System.out.println("Contraseña igual");
                    
                    frameMenu mn = new frameMenu();
                    mn.setVisible(true);
                    this.dispose();
                    errorCon.setIcon(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "La Contraseña no coincide", JOptionPane.ERROR_MESSAGE);
                    errorContraseña();
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario no existe", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
                errorUsuario();
            }
        } else {
            JOptionPane.showMessageDialog(null, ""+mensaje,"Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnAcercaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaMouseExited
        btnAcerca.setBackground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_btnAcercaMouseExited

    private void btnAcercaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaMouseEntered
        btnAcerca.setBackground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnAcercaMouseEntered

    private void btnAcercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaMouseClicked
        FrmAcerca acr = new FrmAcerca();
        acr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcercaMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        minbtn.setBackground(new java.awt.Color(89,89,89));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseEntered
        minbtn.setBackground(new java.awt.Color(120,120,120));
    }//GEN-LAST:event_btnMinMouseEntered

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        this.setExtendedState(frameLogin.ICONIFIED);
    }//GEN-LAST:event_btnMinMouseClicked

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        exitbtn.setBackground(new java.awt.Color(89,89,89));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        exitbtn.setBackground(new java.awt.Color(211,77,77));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    boolean mouseDentro = true;
    private void campoUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && mouseDentro){
            btnIngresarMouseClicked(null);
        }
    }//GEN-LAST:event_campoUsuKeyPressed

    private void campoConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoConKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && mouseDentro){
            btnIngresarMouseClicked(null);
        }
    }//GEN-LAST:event_campoConKeyPressed

    int xMouse = 0, yMouse = 0;    
    boolean mostrarContrasena = false;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acerca;
    private javax.swing.JLabel Ingresar;
    private javax.swing.JLabel LoginBackrgound;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel TItulo;
    private javax.swing.JPanel btnAcerca;
    private javax.swing.JLabel btnExit;
    private javax.swing.JPanel btnIngresar;
    private javax.swing.JLabel btnMin;
    private javax.swing.JPasswordField campoCon;
    private javax.swing.JTextField campoUsu;
    private javax.swing.JLabel errorCon;
    private javax.swing.JLabel errorUs;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel minbtn;
    private javax.swing.JLabel passicon;
    private javax.swing.JSeparator sepCon;
    private javax.swing.JSeparator sepUs;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
